---

- name: Set repository
  template: src=centos-base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo
  when: utils_repository is defined

- name: Check EPEL repository
  shell: 'yum repolist | grep ^epel | cut -f1 -d\ '
  register: epel_enabled
  changed_when: false
  tags:
    - install
    - utils

- name: Downloading and enable the EPEL repository definitions.
  command: rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  when: epel_enabled.stdout != 'epel'
  tags:
    - install
    - utils

- name: Update packages 
  yum: name=* state=latest
  tags:
    - install
    - utils
    - update

- name: Install utils
  yum: name={{item}} state=present
  with_items: utils_packages
  tags:
    - install
    - utils

# cpufreq-scaling

